M48
; DRILL file {KiCad 7.0.1} date Wed Sep 13 21:21:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-13T21:21:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.4677Y-2.9453
X4.4677Y-3.1728
T2
X4.7886Y-4.4591
X4.8386Y-2.5591
X6.8386Y-3.1591
X6.8386Y-4.2591
T0
M30
